# Generated by Django 4.0.4 on 2023-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_postratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postratingmodel',
            name='is_like',
            field=models.BooleanField(blank=True, default=False, help_text='<small class="text-muted">BooleanField</small><hr><br>', verbose_name='Рейтинг'),
        ),
    ]
