# Generated by Django 4.1.7 on 2023-02-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
